### PR TITLE
made nav width adjustable

### PR DESCRIPTION
**Pull request by prasoonmhwr**
- https://github.com/Icon-Shelf/icon-shelf/issues/75

### CODE REVIEW

**Comment by prasoonmhwr** [comment]
@MrRobz i think the check is failing because I added a new library(re-sizable) in package.json, any idea how this can be fixed.

**Comment by prasoonmhwr** [comment]
@MrRobz Even after updating lock file its failing

**Comment by MrRobz** [comment]
> @MrRobz Even after updating lock file its failing

Yup I can see that. Wondering what could be the issue.

**Comment by prasoonmhwr** [comment]
> > @MrRobz Even after updating lock file its failing
> 
> Yup I can see that. Wondering what could be the issue.

I think this is happening becasue of the npm and node version mismatch, I am using 

Node: v16.15.0
npm: 8.5.5

what is the version used in project?

**Comment by MrRobz** [comment]
> > > @MrRobz Even after updating lock file its failing
> > 
> > 
> > Yup I can see that. Wondering what could be the issue.
> 
> I think this is happening becasue of the npm and node version mismatch, I am using
> 
> Node: v16.15.0 npm: 8.5.5
> 
> what is the version used in project?

The github action that runs lint and type checks have node 16 and npm 8.

**Comment by prasoonmhwr** [comment]
> 

so i think its not the version issue then

**Comment by MrRobz** [comment]
> > 
> 
> so i think its not the version issue then

What puts me off is, the github action logs says

npm ERR! Missing: @types/estree@0.0.51 from lock file
npm ERR! Missing: @webassemblyjs/ast@1.11.1 from lock file
npm ERR! Missing: @webassemblyjs/wasm-edit@1.11.1 from lock file

But packages are not there in package-lock files. Why is it trying to install them !

**Comment by prasoonmhwr** [comment]
> 

Not sure , Actually I am new to github so no experience with github actions, sorry about that.

**Review by MrRobz — APPROVED** [review]
Thanks for your changes @prasoonmhwr .
I don't see any thing wrong with the PR that is causing the github action to fail.
Could be something wrong with the action runns in github for forked repos.

I'll try merging to a separate branch in icon-shelf repo test it and then merge to the main repo.

Thank again. This is amazing work.

**Comment by prasoonmhwr** [comment]
@MrRobz Found something on the internet, it was an accepted answer on stackoverflow, can we try this?

``` 
     - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
```

**Comment by prasoonmhwr** [comment]
> Thanks for your changes @prasoonmhwr . I don't see any thing wrong with the PR that is causing the github action to fail. Could be something wrong with the action runns in github for forked repos.
> 
> I'll try merging to a separate branch in icon-shelf repo test it and then merge to the main repo.
> 
> Thank again. This is amazing work.

@MrRobz Please let me know if it gets merged into the main branch . It will make me feel happy :)

**Comment by MrRobz** [comment]
> @MrRobz Found something on the internet, it was an accepted answer on stackoverflow, can we try this?
> 
> ```
>      - name: Install dependencies
>         run: |
>           if [ -e yarn.lock ]; then
>           yarn install --frozen-lockfile
>           elif [ -e package-lock.json ]; then
>           npm ci
>           else
>           npm i
>           fi
> ```

Got it working here https://github.com/Icon-Shelf/icon-shelf/pull/121
it was something to do with package-lock file. I reverted package-lock file to original version and did `npm install  re-resizable`.
Merging it to main now.

**Pull request merged**
